name: Transform Inputs
description: Transform the "Trigger GitHub Action" payload

inputs:
  fileKey:
    description: Figma file key
    required: true
  page:
    description: Stringified selected page (id, name)
    required: true
  selection:
    description: Stringified array of the selected nodes (id, name)
    required: true

outputs:
  fileKey:
    description: Figma file key
  ids:
    description: Stringified array of ids to export

runs:
  using: node20
  main: main.js
