name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Figma Export PDFs 🦾
        id: figmaExportPdfs
        uses: ./
        with:
          accessToken: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          fileKey: 'VQxKo2pnaksjE7Vql999Qv'
          ids: '["120:3","138:28"]'

      - name: Log ℹ️
        run: |
          echo "Results"
          echo "pdfs: $pdfs"
          echo "outDir: $outDir"
        env:
          pdfs: ${{ steps.figmaExportPdfs.outputs.pdfs }}
          outDir: ${{ steps.figmaExportPdfs.outputs.outDir }}

      - name: Upload artifact 📂
        uses: actions/upload-artifact@v4
        with:
          name: my-pdfs
          path: ${{ steps.figmaExportPdfs.outputs.outDir }}
