name: Dispatch

on:
  workflow_dispatch:
    inputs:
      fileKey:
        description: Figma File key
        type: string
        required: true
      ids:
        description: Stringified array of ids to export
        type: string
        default: '[]'
        required: true

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Figma Export PDFs 🦾
        id: figmaExportPdfs
        uses: ./
        with:
          accessToken: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          fileKey: ${{ github.event.inputs.fileKey }}
          ids: ${{ github.event.inputs.ids }}

      - name: Log ℹ️
        run: |
          echo "Results"
          echo "pdfs: $pdfs"
          echo "outDir: $outDir"
        env:
          pdfs: ${{ steps.figmaExportPdfs.outputs.pdfs }}
          outDir: ${{ steps.figmaExportPdfs.outputs.outDir }}

      - name: Upload artifact 📂
        uses: actions/upload-artifact@v4
        with:
          name: my-pdfs
          path: ${{ steps.figmaExportPdfs.outputs.outDir }}

      - name: FTP Upload 📂
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ${{ steps.figmaExportPdfs.outputs.outDir }}
          server-dir: ./pdf-test/
